"""added some more columns in project

Revision ID: 3abd4aea649b
Revises: fc60d4fe31bf
Create Date: 2026-05-05 23:15:33.236142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abd4aea649b'
down_revision: Union[str, None] = 'fc60d4fe31bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_users', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
