"""Add assignee_name to tasks and fix models

Revision ID: 5297f9d5319f
Revises: 9973c0e29f1a
Create Date: 2026-05-08 17:16:00.764609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5297f9d5319f'
down_revision: Union[str, None] = '9973c0e29f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('projects', sa.Column('name', sa.String(), nullable=True))
    op.drop_index('ix_projects_title', table_name='projects')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.drop_column('projects', 'title')
    op.add_column('tasks', sa.Column('assignee_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'assignee_name')
    op.add_column('projects', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_index('ix_projects_title', 'projects', ['title'], unique=False)
    op.drop_column('projects', 'name')
    op.drop_column('project_users', 'created_at')
    # ### end Alembic commands ###
