"""Re-add project_users column to projects

Revision ID: 8bf7e1029b19
Revises: 3abd4aea649b
Create Date: 2026-05-05 23:37:30.811692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf7e1029b19'
down_revision: Union[str, None] = '3abd4aea649b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_users', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_users')
    # ### end Alembic commands ###
