"""updated column of the project

Revision ID: 8ceac65a6f4b
Revises: 5297f9d5319f
Create Date: 2026-05-08 19:46:17.066311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ceac65a6f4b'
down_revision: Union[str, None] = '5297f9d5319f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.String(), nullable=True))
    op.drop_index('ix_projects_name', table_name='projects')
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.drop_column('projects', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.drop_column('projects', 'title')
    # ### end Alembic commands ###
