"""update column name to title over name for the projects table

Revision ID: 9973c0e29f1a
Revises: d4592a3b092b
Create Date: 2026-05-07 13:54:56.190841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9973c0e29f1a'
down_revision: Union[str, None] = 'd4592a3b092b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.String(), nullable=True))
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_index('ix_projects_project_owner_id', table_name='projects')
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.drop_column('projects', 'name')
    op.drop_column('projects', 'project_owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.create_index('ix_projects_project_owner_id', 'projects', ['project_owner_id'], unique=False)
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.drop_column('projects', 'title')
    # ### end Alembic commands ###
