"""fix updated at column to avoding the null pricipal

Revision ID: b9ea8d38bd4c
Revises: 8ceac65a6f4b
Create Date: 2026-05-08 20:05:37.997144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ea8d38bd4c'
down_revision: Union[str, None] = '8ceac65a6f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
