"""add project_users table

Revision ID: d4592a3b092b
Revises: 1f6e3f9d2a4b
Create Date: 2026-05-06 17:39:55.871121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4592a3b092b'
down_revision: Union[str, None] = '1f6e3f9d2a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_users_id'), 'project_users', ['id'], unique=False)
    op.create_index(op.f('ix_project_users_project_id'), 'project_users', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_users_user_id'), 'project_users', ['user_id'], unique=False)
    op.drop_column('projects', 'project_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_users', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_project_users_user_id'), table_name='project_users')
    op.drop_index(op.f('ix_project_users_project_id'), table_name='project_users')
    op.drop_index(op.f('ix_project_users_id'), table_name='project_users')
    op.drop_table('project_users')
    # ### end Alembic commands ###
